// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTvFLcxHLYXXUQXq_7tfj9kEi0xExc5rA',
    appId: '1:366404433530:web:a106bb9fe3fdf2df3bedc3',
    messagingSenderId: '366404433530',
    projectId: 'steermate-736dd',
    authDomain: 'steermate-736dd.firebaseapp.com',
    storageBucket: 'steermate-736dd.firebasestorage.app',
    measurementId: 'G-8YVV0EB4KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaNNKugWPMJYI_LrJHqj3i9rAFjUIJfas',
    appId: '1:366404433530:android:7d429b13943d3af23bedc3',
    messagingSenderId: '366404433530',
    projectId: 'steermate-736dd',
    storageBucket: 'steermate-736dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDShokIVpY3CYMSvU8GcZiZCM6-Be4v16A',
    appId: '1:366404433530:ios:94c04b4b40fd5b883bedc3',
    messagingSenderId: '366404433530',
    projectId: 'steermate-736dd',
    storageBucket: 'steermate-736dd.firebasestorage.app',
    iosBundleId: 'com.example.smate',
  );
}
