// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyeCMDuRMq5zMwzLiQ9nTfBATVyhjguv0',
    appId: '1:42777815746:web:31d632d96e4de54dace95b',
    messagingSenderId: '42777815746',
    projectId: 'smate-driving',
    authDomain: 'smate-driving.firebaseapp.com',
    storageBucket: 'smate-driving.firebasestorage.app',
    measurementId: 'G-VDE8EW86VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEutdYFz7ScHxYqqCLkimfiDI2MxXVUhk',
    appId: '1:42777815746:android:df3b5dc38c2e8a3dace95b',
    messagingSenderId: '42777815746',
    projectId: 'smate-driving',
    storageBucket: 'smate-driving.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhjxRkIT6TNudFi1tQh1aCCjuhuovR6a0',
    appId: '1:42777815746:ios:7128eefbc4293b53ace95b',
    messagingSenderId: '42777815746',
    projectId: 'smate-driving',
    storageBucket: 'smate-driving.firebasestorage.app',
    iosBundleId: 'com.example.smate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhjxRkIT6TNudFi1tQh1aCCjuhuovR6a0',
    appId: '1:42777815746:ios:7128eefbc4293b53ace95b',
    messagingSenderId: '42777815746',
    projectId: 'smate-driving',
    storageBucket: 'smate-driving.firebasestorage.app',
    iosBundleId: 'com.example.smate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyeCMDuRMq5zMwzLiQ9nTfBATVyhjguv0',
    appId: '1:42777815746:web:edba897eeb954dd9ace95b',
    messagingSenderId: '42777815746',
    projectId: 'smate-driving',
    authDomain: 'smate-driving.firebaseapp.com',
    storageBucket: 'smate-driving.firebasestorage.app',
    measurementId: 'G-RLMMCK7CC9',
  );
}
